### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by mr-tz** [williballenthin/viv-utils#152]
Can you please publish a new version? :)

**Comment by williballenthin** [comment]
next time i'm at my ⌨️!

**Comment by mr-tz** [comment]
:bow: feel free to add me as a maintainer as well (I expect some work here as part of https://github.com/mandiant/capa/issues/989 soon)

**Comment by williballenthin** [comment]
https://github.com/williballenthin/viv-utils/releases/tag/v0.7.10

**Comment by williballenthin** [comment]
I'll add you as a maintainer next time I have my security key handy (tomorrow?)

**Comment by williballenthin** [comment]
![image](https://github.com/williballenthin/viv-utils/assets/156560/a20ca334-8276-468a-9384-b739e52f8d58)
ugh need to update auth to PyPI and try again. maybe i can do this tomorrow.

**Comment by mr-tz** [comment]
bump :)

**Comment by williballenthin** [comment]
https://pypi.org/project/viv-utils/0.7.10/
