### ISSUE TITLE
set max_instruction_count

### ISSUE THREAD

**Issue by mr-tz** [williballenthin/viv-utils#33]
https://github.com/williballenthin/viv-utils/blob/5ef832393bf95228c9dffcc2b0ec79824fd8e19b/viv_utils/emulator_drivers.py#L488-L497

is this missing when used via `run`?

**Comment by williballenthin** [comment]
use `max_insn` on the driver constructor.

i'll remove this old kwarg.

**Comment by williballenthin** [comment]
i moved this arg to the constructor for consistency, and because i dont imagine the setting would be changed from run to run. open to changing back if you'd prefer.
