### ISSUE TITLE
feature: add driver to emulate path(s) from startva to endva

### ISSUE THREAD

**Issue by mr-tz** [williballenthin/viv-utils#37]
yes, lets add another driver with specific behavior for tight loops.

_Originally posted by @williballenthin in https://github.com/williballenthin/viv-utils/pull/35#discussion_r837713233_

**Comment by williballenthin** [comment]
we can put this driver within the FLOSS project, unless we expect it to be used by other projects

**Comment by mr-tz** [comment]
true, I think "forcing" emulation down a specific code path or finding the paths could be useful for other projects

**Comment by mr-tz** [comment]
implemented via the `SinglePathEmulatorDriver` in #35
